@echo off

SET PROJECT_FOLDER=MDK-ARM
SET KEIL_PROJECT_NAME_UVPROJX=GM6020_demo.uvprojx

SET PRODUCTION_FOLDER=Production
SET TMP_FOLDER=ci_tmp
SET BUILD_LOG=build.log

IF "%PROJECT_TARGET%"=="GM6020_demo" (
	SET KEIL_PROJECT_OUTPUT_DIR=GM6020_demo\
	SET KEIL_PROJECT_LISTING_DIR=
	SET KEIL_PROJECT_OPTIM_LEVEL=4
)
SET PROJECT_TARGET_LIST[0]=GM6020_demo
SET KEIL_PROJECT_OUTPUT_DIR_LIST[0]=GM6020_demo\
SET KEIL_PROJECT_LISTING_DIR_LIST[0]=
SET KEIL_PROJECT_OPTIM_LEVEL_LIST[0]=4

SET PROJECT_TARGET_LIST_LENGTH=0
